### ISSUE TITLE
Try to run source

### ISSUE THREAD

**Issue by catinapoke** [msoap/shell2telegram#12]
![default](https://user-images.githubusercontent.com/22505407/46148771-7718b100-c271-11e8-9d50-7a57fe1a9757.png)

This is putty screen, on path go/src/shell2telegram/ I placed shell2telegram, when i try run 1 .go file, linux see him, but when i try to run project he don't see. can't fix it, help me pls

![default](https://user-images.githubusercontent.com/22505407/46149308-af6cbf00-c272-11e8-8eba-26faf2f3d984.png)

**Comment by catinapoke** [comment]
well, i did more correctly run this, but 
![default](https://user-images.githubusercontent.com/22505407/46149257-949a4a80-c272-11e8-9044-13c89719de7f.png)

**Comment by msoap** [comment]
Yes, is correct, you need two parameters: `/bot_command` and `shell command`, for example:
```
go run commands.go shell2telegram.go users.go utils.go /date 'date'
```

or see help:
```
go run commands.go shell2telegram.go users.go utils.go -help

```

**Comment by catinapoke** [comment]
Okay, but how i can use any commands in me shell, line /usecommand "commandname with params"? or i can't?

**Comment by msoap** [comment]
Yes, you can use any commands that print text

**Comment by catinapoke** [comment]
I just send to bot "top"(How i can stop top?) or "ls -a" and bot perform it?

**Comment by msoap** [comment]
Yes, but the telegram command must start at `/` - `/top` not `top`

**Comment by msoap** [comment]
Like this:
```
go run commands.go shell2telegram.go users.go utils.go /ls 'ls -a' /top 'ps aux'
```

**Comment by catinapoke** [comment]
Well, i write
go run commands.go shell2telegram.go users.go utils.go /top 'top' /ipconfig 'ipconfig'
(don't write /lsa 'ls -a') and if i write /ls -a will it perform 'ls -a' command?

**Comment by catinapoke** [comment]
oh, i just think that sh2tg have universal way to perform commands

**Comment by msoap** [comment]
For use parameters for shell commands, you can use vars, like this:
```
shell2telegram /alarm:vars=SLEEP,MSG 'sleep $SLEEP; echo Alarm: $MSG'
```

**Comment by catinapoke** [comment]
Okay, thank you, i will try it
