### ISSUE TITLE
Add option to format output message as code block

### ISSUE THREAD

**Issue by k3lwin** [msoap/shell2telegram#14]
See [description](https://core.telegram.org/api/entities)

Code block formatted replies would be significantly more readable, especially for multiline output from commands like `systemctl status`.

**Comment by msoap** [comment]
Hello,

you can use `:md` suffix for command, see [modificators](https://github.com/msoap/shell2telegram#modificators-for-bot-commands), and 3 backticks around output of your shell command:

for example:
```
shell2telegram /cal:md 'echo "\`\`\`$(ncal)\`\`\`"'
```

result in Telegram:
<img width="504" alt="Screenshot 2021-04-22 at 21 29 15 " src="https://user-images.githubusercontent.com/844117/115767718-11055380-a3b2-11eb-8f96-1fda61fcf338.png">
